# Generated by Django 4.2.5 on 2023-10-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmergencias',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('codigoColor', models.TextField(max_length=20)),
                ('fecha', models.DateTimeField(max_length=30)),
                ('nro_pacientes', models.IntegerField(max_length=5)),
            ],
        ),
    ]
