# Generated by Django 4.2.5 on 2023-10-14 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HoraDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraInicio', models.TimeField(default=django.utils.timezone.now)),
                ('HoraFin', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rut', models.IntegerField()),
                ('Dv', models.CharField(max_length=1)),
                ('PrimerNombre', models.TextField(max_length=20)),
                ('SegundoNombre', models.TextField(max_length=20, null=True)),
                ('ApellidoPaterno', models.TextField(max_length=20)),
                ('ApellidoMaterno', models.TextField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmergencias',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(max_length=50)),
                ('CodigoColor', models.TextField(max_length=20)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now, max_length=30)),
                ('NumeroPacientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.persona')),
            ],
            bases=('principal.persona',),
        ),
        migrations.CreateModel(
            name='DoctorClave',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.persona')),
                ('Area', models.TextField(max_length=30)),
            ],
            bases=('principal.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.persona')),
            ],
            bases=('principal.persona',),
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.persona')),
            ],
            bases=('principal.persona',),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clase', models.CharField(max_length=100)),
                ('DiaHora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.horadia')),
                ('DiaSemana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEmergencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Detalles', models.TextField()),
                ('Emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.registroemergencias')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDoctoresEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAsignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.registroemergencias')),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.doctorclave')),
            ],
        ),
        migrations.AddField(
            model_name='registroemergencias',
            name='Doctores',
            field=models.ManyToManyField(through='principal.HistorialDoctoresEmergencia', to='principal.doctorclave'),
        ),
        migrations.AddField(
            model_name='doctorclave',
            name='Horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.horario'),
        ),
    ]
