# Generated by Django 4.2.5 on 2023-10-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroemergencias',
            name='nro_pacientes',
            field=models.IntegerField(),
        ),
    ]
