# Generated by Django 4.2.5 on 2023-10-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_registroemergencias_nro_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.TextField(max_length=20)),
                ('seg_nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('seg_apellido', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doctorClave',
            fields=[
                ('rut', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.TextField(max_length=20)),
                ('seg_nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('seg_apellido', models.TextField(max_length=20)),
                ('area', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HoraDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.TextField(max_length=20)),
                ('seg_nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('seg_apellido', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('rut', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.TextField(max_length=20)),
                ('seg_nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('seg_apellido', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=100)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.diasemana')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.horadia')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEmergencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('detalles', models.TextField()),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.registroemergencias')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDoctoresEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.doctorclave')),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.registroemergencias')),
            ],
        ),
        migrations.AddField(
            model_name='doctorclave',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.horario'),
        ),
        migrations.AddField(
            model_name='registroemergencias',
            name='doctores',
            field=models.ManyToManyField(through='principal.HistorialDoctoresEmergencia', to='principal.doctorclave'),
        ),
    ]
